# This is github-action CI pipeline for product-catalog-micro-file

name: Product-Catalog CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code        # Checkout Code [ Clone the repository ] 
        uses: actions/checkout@v2

      - name: Setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build Project
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog main.go
      
      - name: Run Unit Test Cases
        run: | 
          cd src/product-catalog
          go test -v ./...

    code-quality:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
       
        - name: Run Golang CI Lint
          run: |
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
            golangci-lint run src/product-catalog/...

    docker:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2

        - name: Install Docker
          uses: docker/setup-buildx-action@v1

        - name: Docker Login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN}}

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: src/product-catalog
            file: Dockerfile 
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog-micro-service:${{ github.run_id }}
        
    update-k8s:
      runs-on: ubuntu-latest
      needs: docker
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.TOKEN }}
        - name: Update Kubernetes Manifest
          run: |
            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/product-catalog-micro-service:${{github.run_id}}|" kubernetes/productcatalog/deploy.yaml

        - name: Commit and Push Changes
          run: |
            git config --local user.email "${{ secrets.GIT_EMAIL }}"
            git config --local user.name "${{ secrets.GIT_NAME }}"
            git add kubernetes/productcatalog/deploy.yaml
            git commit -m "[Actions-CI]Update Kubernetes manifest"
            git push
